<template>
  <v-app>
    <v-toolbar app dark color="pink">
      <v-toolbar-title>Search the News</v-toolbar-title>
    </v-toolbar>

  <main>
    <v-content>
      <v-container fluid mt-5>
        <v-layout align-center justify-center>
          <v-flex
            xs12
            md6
            lg6>
        <v-form ref="form">
          <v-text-field
            label="Search the news"
            v-model="search"
            value='search'
            >
          </v-text-field>
          <!-- TODO: CHANGE FROM MOCK CALL!! -->
          <v-btn @click="MOCKfetchNews">Search</v-btn>        
        </v-form>
        </v-flex>
      </v-layout>
    </v-container>

    <Sentiment v-if="showResults" :overallSentiment="overallSentiment" :overallScore="overallScore" />
    <NewsCards v-if="showResults" v-bind:articles="this.articles"/>

    </v-content>
    </main>
  </v-app>
</template>

<script>
import NewsCards from './NewsCards';
import Sentiment from './Sentiment';
import mockData from '../assets/MOCK_DATA.json';
import axios from 'axios';

export default {
  name: 'HelloWorld',
  components: {
    NewsCards,
    Sentiment
  },
  data() {
    return {
      search: '',
      showResults: false,
      mostNegative: '',
      mostPositive: '',
      loading: false,
      overallScore: 2,
      overallSentiment: 21,
      articles: [...mockData]
    };
  },
  methods: {
    MOCKfetchNews() {
      this.overallScore = 62;
      this.overallSentiment = this.overallScore / 30;
    },

    getNews: input => {
      return axios.get(
        'https://newsapi.org/v2/everything?apiKey=cffd5c18704145eb89a7156717753b11',
        {
          params: {
            // apiKey: 'cffd5c18704145eb89a7156717753b11',
            q: `+"${input}"-APKMirror`,
            from: '2018-4-15',
            language: 'en',
            sortBy: 'relevancy',
            sources:
              'bbc-news, abc-news, business-insider, cbs-news, cnbc, cnn, engadget, financial-times, fox-news, nbc-news, the-huffington-post, the-new-york-times, the-wall-street-journal, the-washington-post, usa-today, wired, time, the-economist, the-american-conservative',
            // REMOVE PAGE
            pageSize: 5
            // country: 'us',
          }
        }
      );
    },

    // PASS IN URL
    getEmotion(url) {
      return axios.get('https://api.dandelion.eu/datatxt/sent/v1', {
        dataType: 'json',
        params: {
          token: 'b97f5af544e14020b0887beef8e4a577',
          url: url
        }
      });
    },

    fetchNews(input) {
      this.loading = true;
      this.getNews(input).then(res => {
        this.loading = false;
        res.data.articles.map(article => this.articles.push(article));
        this.isArticles = true;
        console.log(this.isArticles);
        console.log(this.articles);
        let urls = [...res.data.articles.map(article => article.url)];
        // now call the getEmotion with urls generated by getNews
        urls.map(url => {
          this.getEmotion(url)
            .then(res => {
              this.overallScore += res.data.sentiment.score;
              console.log(res.data.url);
              console.log(res.data.sentiment.score);
            })
            .then(() => {
              this.overallSentiment = this.overallScore / 5;
            });
        });
      });
    }
  }
};
</script>


<style >

</style>
